---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: simple-node-service
  name: simple-node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      application: simple-node-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: simple-node-service
        tier: nodejs
      name: simple-node-service
    spec:
      containers:
      - image: grabnerandi/simplenodeservice:1.0.2
        imagePullPolicy: IfNotPresent
        name: simple-node-service
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          requests:
            cpu: "100m"
            memory: "300Mi"
          limits:
            cpu: "100m"
            memory: "300Mi"