---
apiVersion: v1
kind: Service
metadata:
  labels:
    tier: nodejs
  name: sns-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 80
  selector:
    application: simple-node-service
  sessionAffinity: None
  type: LoadBalancer